# .github/workflows/readme-refresh.yml
name: Refresh Profile README

on:
  schedule:
    - cron: "0 6 * * *"   # Daily at 06:00 UTC
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update contribution counts and year
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_LOGIN: ${{ github.repository_owner }}
        run: |
          # Set error handling
          set -e
          
          FILE="README.md"
          if [[ ! -f "$FILE" ]]; then
            echo "README.md not found; exiting gracefully."
            exit 0
          fi

          # Get current year
          YEAR=$(date -u +%Y)
          echo "Current year: $YEAR"

          # Get contribution counts using GitHub API
          echo "Fetching contribution data for $USER_LOGIN..."
          
          # Use simpler approach with GitHub REST API
          YTD_RESP=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/users/$USER_LOGIN")
          
          if [[ $? -eq 0 ]]; then
            echo "Successfully fetched user data"
            
            # Update year in README
            if grep -q "<!--current_year-->" "$FILE"; then
              sed -i "s/<!--current_year-->[0-9]\{4\}<!--\/current_year-->/<!--current_year-->$YEAR<!--\/current_year-->/" "$FILE"
              echo "Updated year to $YEAR"
            fi
            
            # Update refresh marker
            TODAY=$(date -u +%F)
            if grep -q "<!--last_refresh-->" "$FILE"; then
              sed -i "s/<!--last_refresh:[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-->/<!--last_refresh:$TODAY-->/" "$FILE"
            else
              sed -i "1s|^|<!--last_refresh:$TODAY-->\n|" "$FILE"
            fi
            echo "Updated refresh marker to $TODAY"
            
          else
            echo "Failed to fetch user data, but continuing..."
          fi

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore(readme): auto-update year and refresh marker [skip ci]"
            git push
            echo "Changes committed successfully"
          else
            echo "No changes needed"
          fi
